import React,{useEffect,useRef,useState} from 'react';
import {Download,Expand,Minus,Plus,X} from 'lucide-react';
import {segmentPoints} from './metrobusLayout';
const official='/metrobus-oficial.jpg',W=1368,H=1824;
const asPoints=points=>points.map(point=>point.join(',')).join(' ');
const overlap=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function placeLabels(labels){const used=[];return labels.filter(label=>label.point).map(label=>{const [px,py]=label.point,text=`${label.kind}: ${label.name}`,w=Math.min(300,Math.max(146,text.length*7.3+26)),h=34,candidates=[[px+20,py-34],[px+20,py+16],[px-w-20,py-34],[px-w-20,py+16],[px-60,py-58]];const box=candidates.map(([x,y])=>({x:Math.max(16,Math.min(W-w-16,x)),y:Math.max(16,Math.min(H-h-16,y)),w,h})).find(item=>used.every(other=>!overlap(item,other)))||{x:Math.max(16,Math.min(W-w-16,px+20)),y:Math.max(16,Math.min(H-h-16,py+48)),w,h};used.push(box);return {...label,text,...box}})}
function viewBoxFor(points){if(!points.length)return `0 0 ${W} ${H}`;const xs=points.map(point=>point[0]),ys=points.map(point=>point[1]),span=Math.max(Math.max(...xs)-Math.min(...xs),Math.max(...ys)-Math.min(...ys)),pad=Math.max(120,Math.min(250,span*.24)),left=Math.max(0,Math.min(...xs)-pad),top=Math.max(0,Math.min(...ys)-pad),right=Math.min(W,Math.max(...xs)+pad),bottom=Math.min(H,Math.max(...ys)+pad);return `${left} ${top} ${right-left} ${bottom-top}`}
export default function MetrobusMap({route}){
 const [full,setFull]=useState(false),[zoom,setZoom]=useState(1),[officialMap,setOfficialMap]=useState(!route),svg=useRef(null);
 useEffect(()=>{setOfficialMap(!route);setZoom(1)},[route]);useEffect(()=>{if(!full)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[full]);
 const segments=route?.segments||[],segmentData=segments.map(segment=>({...segment,points:segmentPoints(segment)}));
 const connectors=segmentData.slice(1).map((segment,index)=>({from:segmentData[index].points.at(-1),to:segment.points[0],name:segment.stations[0]})).filter(item=>item.from&&item.to);
 const labels=route?[{name:segments[0].stations[0],point:segmentData[0].points[0],kind:'Origen'},...connectors.map(item=>({name:item.name,point:[(item.from[0]+item.to[0])/2,(item.from[1]+item.to[1])/2],kind:'Transbordo'})),{name:segments.at(-1).stations.at(-1),point:segmentData.at(-1).points.at(-1),kind:'Destino'}]:[];
 const arranged=placeLabels(labels),focus=[...segmentData.flatMap(segment=>segment.points),...connectors.flatMap(item=>[item.from,item.to]),...arranged.flatMap(label=>[[label.x,label.y],[label.x+label.w,label.y+label.h]])];
 function download(){if(!svg.current)return;const copy=svg.current.cloneNode(true);copy.setAttribute('xmlns','http://www.w3.org/2000/svg');const [,,,viewWidth,viewHeight]=copy.getAttribute('viewBox').split(' ').map(Number),width=1600,height=Math.round(width*viewHeight/viewWidth);copy.setAttribute('width',String(width));copy.setAttribute('height',String(height));const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(copy)],{type:'image/svg+xml'})),image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;canvas.getContext('2d').drawImage(image,0,0);URL.revokeObjectURL(url);canvas.toBlob(png=>{const link=document.createElement('a');link.href=URL.createObjectURL(png);link.download='mi-ruta-metrobus.png';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)})};image.src=url}
 return <section className={'mb-map'+(full?' mb-map-full':'')} aria-label="Mapa de Metrobús"><div className="mb-map-tools"><div><button onClick={()=>{setOfficialMap(true);setZoom(1)}} aria-pressed={officialMap}>Red oficial</button><button disabled={!route} onClick={()=>{setOfficialMap(false);setZoom(1)}} aria-pressed={!officialMap}>Mi ruta</button></div><div><button title="Alejar" onClick={()=>setZoom(value=>Math.max(1,value-.5))}><Minus size={17}/></button><button title="Acercar" onClick={()=>setZoom(value=>Math.min(3,value+.5))}><Plus size={17}/></button><button title={full?'Cerrar mapa':'Expandir mapa'} onClick={()=>setFull(value=>!value)}>{full?<X size={17}/>:<Expand size={17}/>}</button>{!officialMap&&route&&<button title="Descargar ruta PNG" onClick={download}><Download size={17}/></button>}</div></div><div className="mb-map-viewport">{officialMap?<div className="mb-map-stage" style={{width:zoom*100+'%'}}><img src={official} alt="Plano oficial de las siete líneas del Metrobús CDMX"/></div>:<svg ref={svg} className="mb-route-map" xmlns="http://www.w3.org/2000/svg" viewBox={viewBoxFor(focus)} style={{width:zoom*100+'%'}} role="img" aria-label="Ruta de Metrobús"><rect width={W} height={H} fill="#fffafa"/>{segmentData.map((segment,index)=><g key={index}><polyline points={asPoints(segment.points)} fill="none" stroke="#d8c7cd" strokeWidth="22" strokeLinecap="round" strokeLinejoin="round"/><polyline points={asPoints(segment.points)} fill="none" stroke="white" strokeWidth="18" strokeLinecap="round" strokeLinejoin="round"/><polyline points={asPoints(segment.points)} fill="none" stroke={segment.line.color} strokeWidth="12" strokeLinecap="round" strokeLinejoin="round"/>{segment.points.map((point,i)=><circle key={i} cx={point[0]} cy={point[1]} r="4.5" fill="white" stroke={segment.line.color} strokeWidth="2.5"/>)}</g>)}{connectors.map((connector,index)=><g key={index}><line x1={connector.from[0]} y1={connector.from[1]} x2={connector.to[0]} y2={connector.to[1]} stroke="white" strokeWidth="16" strokeLinecap="round"/><line x1={connector.from[0]} y1={connector.from[1]} x2={connector.to[0]} y2={connector.to[1]} stroke="#be1830" strokeWidth="7" strokeDasharray="8 8" strokeLinecap="round"/></g>)}{arranged.map((label,index)=><g key={`${label.name}-${index}`}><circle cx={label.point[0]} cy={label.point[1]} r="14" fill="white" stroke="#be1830" strokeWidth="6"/><rect x={label.x} y={label.y} width={label.w} height={label.h} rx="8" fill="white" stroke="#ead8dc" strokeWidth="2"/><text x={label.x+10} y={label.y+22} fontFamily="Arial, sans-serif" fontWeight="700" fontSize="13" fill="#33292d">{label.text}</text></g>)}</svg>}</div><p className="mb-map-note">{officialMap?'Plano oficial del sistema · Amplía o mueve el mapa para leerlo.':'Los transbordos se unen con una línea punteada para mostrar la continuidad del viaje.'}</p></section>
}
