const definitions=[
['1','#c9212c','Indios Verdes|Deportivo 18 de Marzo|Euzkaro|Potrero|La Raza|Circuito|San Simón|Manuel González|Buenavista|El Chopo|Revolución|Plaza de la República|Reforma|Hamburgo|Insurgentes|Durango|Álvaro Obregón|Sonora|Campeche|Chilpancingo|Nuevo León|Río Piedad|Polifórum|Nápoles|Col. del Valle|Ciudad de los Deportes|Parque Hundido|Félix Cuevas|Río Churubusco|Teatro Insurgentes|José María Velasco|Francia|Olivo|Altavista|La Bombilla|Doctor Gálvez|Ciudad Universitaria|Centro Cultural Universitario|Perisur|Villa Olímpica|Corregidora|Ayuntamiento|Fuentes Brotantes|Santa Úrsula|La Joya|El Caminero'],
['2','#8a2be2','Tepalcates|General Antonio de León|Nicolás Bravo|Canal de San Juan|Constitución de Apatzingán|CCH Oriente|Leyes de Reforma|Del Moral|Río Frío|Rojo Gómez|Río Mayo|Río Tecolutla|El Rodeo|UPIICSA|Iztacalco|Goma|Tlacotal|Canela|Metro Coyuya|Coyuya|La Viga|Andrés Molina Enríquez|Las Américas|Xola|Álamos|Centro SCOP|Doctor Vértiz|Etiopía|Amores|Viaducto|Nuevo León|Escandón|Patriotismo|Parque Lira|De la Salle|Antonio Maceo|Tacubaya'],
['3','#4f9c46','Tenayuca|San José de la Escalera|Progreso Nacional|Tres Anegas|Júpiter|La Patera|Poniente 146|Montevideo|Poniente 134|Poniente 128|Magdalena de las Salinas|Coltongo|Cuitláhuac|Héroe de Nacozari|Hospital La Raza|Circuito|Tolnahuac|Tlatelolco|Ricardo Flores Magón|Guerrero|Mina|Hidalgo|Juárez|Balderas|Cuauhtémoc|Jardín Pushkin|Hospital General|Doctor Márquez|Centro Médico|Obrero Mundial|Luz Saviñón|Eugenia|División del Norte|Miguel Laurent|Pueblo Santa Cruz Atoyac'],
['4','#f18b2b','Buenavista|Delegación Cuauhtémoc|Puente de Alvarado|Plaza de la República|Glorieta de Colón|Expo Reforma|Juárez|Plaza San Juan|Eje Central|El Salvador|Isabel La Católica|Museo de la Ciudad|Pino Suárez|Las Cruces|Circunvalación|La Merced|Mercado Sonora|Cecilio Robelo|Eduardo Molina|Hospital Balbuena|Moctezuma|San Lázaro'],
['5','#2a6ecb','Río de los Remedios|314 Memorial New’s Divine|5 de Mayo|Vasco de Quiroga|El Coyol|Preparatoria 3|San Juan de Aragón|Río de Guadalupe|Talismán|Victoria|Oriente 101|Río Santa Coleta|Río Consulado|Canal del Norte|Deportivo Eduardo Molina|Mercado Morelos|Archivo General de la Nación|Moctezuma|Venustiano Carranza|Avenida del Taller|Mixiuhca|Hospital General Troncoso|Metro Coyuya|Recreo|Oriente 116|Colegio de Bachilleres 3|Canal de Apatlaco|Apatlaco|Aculco|Churubusco Oriente|Escuadrón 201|Atanasio G. Sarabia|Ermita Iztapalapa|Ganaderos|Pueblo Los Reyes|Barrio San Antonio|Calzada Taxqueña|Cafetales|ESIME Culhuacán|Manuela Sáenz|La Virgen|Tepetlapa|Las Bombas|Vista Hermosa|Calzada del Hueso|Cañaverales|Muyuguarda|Circuito Cuemanco|DIF Xochimilco|Preparatoria 1'],
['6','#e85a9b','El Rosario|Colegio de Bachilleres 1|De las Culturas|Ferrocarriles Nacionales|UAM Azcapotzalco|Tecnoparque|Norte 59|Norte 45|Montevideo|Lindavista-Vallejo|Instituto del Petróleo|San Bartolo|Instituto Politécnico Nacional|Riobamba|Deportivo 18 de Marzo|La Villa|De los Misterios|Hospital Infantil La Villa|Delegación Gustavo A. Madero|Martín Carrera|Hospital General La Villa|San Juan de Aragón|Gran Canal|Casas Alemán|Pueblo San Juan de Aragón|Loreto Fabela|482|414|416 Oriente|416 Poniente|Deportivo Los Galeana|Ampliación Providencia|Volcán de Fuego|La Pradera|Colegio de Bachilleres 9|Francisco Morazán|Villa de Aragón'],
['7','#1f6d54','Indios Verdes|De los Misterios|Hospital Infantil La Villa|Delegación Gustavo A. Madero|Garrido|Avenida Talismán|Necaxa|Excélsior|Robles Domínguez|Clave|Misterios|Mercado Beethoven|Peralvillo|Tres Culturas|Glorieta Cuitláhuac|Garibaldi|Glorieta Violeta|Hidalgo|El Caballito|Glorieta de Colón|París|Reforma|Hamburgo|La Palma|El Ángel|La Diana|Chapultepec|Gandhi|Antropología|Auditorio|Campo Marte']
];
export const metrobusLines=definitions.map(([id,color,stations])=>({id,color,stations:stations.split('|')}));
export const metrobusStations=[...new Set(metrobusLines.flatMap(line=>line.stations))].sort((a,b)=>a.localeCompare(b,'es'));
export const metrobusStationLines=name=>metrobusLines.filter(line=>line.stations.includes(name));
export function findMetrobusRoute(from,to){if(!metrobusStations.includes(from)||!metrobusStations.includes(to))return null;const queue=metrobusStationLines(from).map(line=>[from,line.id]),seen=new Set(queue.map(item=>item.join('|'))),previous=new Map();let end;while(queue.length){const [station,lineId]=queue.shift();if(station===to){end=[station,lineId];break}for(const line of metrobusStationLines(station)){const i=line.stations.indexOf(station);for(const next of [line.stations[i-1],line.stations[i+1]].filter(Boolean)){const key=next+'|'+line.id;if(!seen.has(key)){seen.add(key);previous.set(key,[station,lineId]);queue.push([next,line.id])}}}}if(!end)return null;const nodes=[];for(let key=end.join('|');key;){const [station,lineId]=key.split('|');nodes.unshift([station,lineId]);const prev=previous.get(key);key=prev?prev.join('|'):null}const segments=[];for(let i=1;i<nodes.length;i++){const [a,id]=nodes[i-1],[b,next]=nodes[i];const line=metrobusLines.find(item=>item.id===next);let seg=segments.at(-1);if(!seg||seg.line.id!==line.id){seg={line,stations:[a]};segments.push(seg)}seg.stations.push(b)}for(const seg of segments){const list=seg.line.stations;seg.direction=list.indexOf(seg.stations[0])<list.indexOf(seg.stations.at(-1))?list.at(-1):list[0]}const stops=segments.reduce((total,seg)=>total+seg.stations.length-1,0);return {segments,stops,transfers:Math.max(0,segments.length-1),minutes:stops*2+Math.max(0,segments.length-1)*4,path:nodes.map(node=>node[0])}}

