import React,{useEffect,useRef,useState} from 'react';
import {Expand,X,Plus,Minus,Download} from 'lucide-react';
import {segmentPoints,stationPoint} from './metrobusLayout';
const official='/metrobus-oficial.jpg';
const W=1368,H=1824;
const asPoints=points=>points.map(point=>point.join(',')).join(' ');

export default function MetrobusMap({route}){
 const [full,setFull]=useState(false),[zoom,setZoom]=useState(1),[network,setNetwork]=useState(!route);const svg=useRef(null);
 useEffect(()=>{setNetwork(!route);setZoom(1)},[route]);
 useEffect(()=>{if(!full)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';const esc=e=>{if(e.key==='Escape')setFull(false)};window.addEventListener('keydown',esc);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',esc)}},[full]);
 const labels=route?[{name:route.segments[0].stations[0],point:stationPoint(route.segments[0].line,route.segments[0].stations[0]),kind:'Origen'},...route.segments.slice(1).map(segment=>({name:segment.stations[0],point:stationPoint(segment.line,segment.stations[0]),kind:'Transbordo'})),{name:route.segments.at(-1).stations.at(-1),point:stationPoint(route.segments.at(-1).line,route.segments.at(-1).stations.at(-1)),kind:'Destino'}]:[];
 async function download(){if(!svg.current)return;const response=await fetch(official);const source=await response.blob();const data=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(source)});const clone=svg.current.cloneNode(true);clone.querySelector('image').setAttribute('href',data);const xml=new XMLSerializer().serializeToString(clone);const url=URL.createObjectURL(new Blob([xml],{type:'image/svg+xml'}));const img=new Image();img.onload=()=>{const canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;canvas.getContext('2d').drawImage(img,0,0);URL.revokeObjectURL(url);canvas.toBlob(png=>{const link=document.createElement('a');link.href=URL.createObjectURL(png);link.download='mi-ruta-metrobus.png';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)})};img.src=url}
 return <section className={'mb-map'+(full?' mb-map-full':'')} aria-label="Mapa de Metrobús"><div className="mb-map-tools"><div><button onClick={()=>{setNetwork(true);setZoom(1)}} aria-pressed={network}>Red oficial</button><button disabled={!route} onClick={()=>{setNetwork(false);setZoom(1)}} aria-pressed={!network}>Mi ruta en el mapa</button></div><div><button title="Alejar" onClick={()=>setZoom(z=>Math.max(1,z-.5))}><Minus size={17}/></button><button title="Acercar" onClick={()=>setZoom(z=>Math.min(4,z+.5))}><Plus size={17}/></button><button title={full?'Cerrar mapa':'Expandir mapa'} onClick={()=>setFull(!full)}>{full?<X size={17}/>:<Expand size={17}/>}</button>{!network&&route&&<button title="Descargar ruta PNG" onClick={download}><Download size={17}/></button>}</div></div><div className="mb-map-viewport"><svg ref={svg} xmlns="http://www.w3.org/2000/svg" viewBox={`0 0 ${W} ${H}`} style={{width:zoom*100+'%',height:'auto'}} role="img" aria-label={network?'Plano oficial de las siete líneas del Metrobús CDMX':'Ruta trazada sobre el plano oficial de Metrobús'}><image href={official} width={W} height={H}/>{!network&&route&&<g>{route.segments.map((segment,index)=>{const points=segmentPoints(segment);return <g key={index}><polyline points={asPoints(points)} fill="none" stroke="white" strokeWidth="16" strokeLinecap="round" strokeLinejoin="round" opacity=".92"/><polyline points={asPoints(points)} fill="none" stroke={segment.line.color} strokeWidth="9" strokeLinecap="round" strokeLinejoin="round"/></g>})}{labels.map((label,index)=>label.point&&<g key={`${label.name}-${index}`}><circle cx={label.point[0]} cy={label.point[1]} r="13" fill="white" stroke="#be1830" strokeWidth="6"/><rect x={label.point[0]+16} y={label.point[1]-31} width={Math.max(104,label.name.length*8+22)} height="38" rx="9" fill="white" opacity=".96"/><text x={label.point[0]+26} y={label.point[1]-14} fontFamily="Arial, sans-serif" fontWeight="700" fontSize="16" fill="#33292d">{label.kind}: {label.name}</text></g>)}</g>}</svg></div><p className="mb-map-note">{network?'Plano oficial del sistema · Amplía o mueve el mapa para leerlo.':'Tu trayecto está trazado sobre el plano oficial. Los puntos muestran origen, destino y transbordos.'}</p></section>
}
