import React,{useEffect,useRef,useState} from 'react';
import {Expand,X,Plus,Minus,Download} from 'lucide-react';
const official='https://metrobus.cdmx.gob.mx/storage/app/media/uploaded-files/Mapa-MI_MB_final.jpg';
export default function MetrobusMap({route}){
 const [full,setFull]=useState(false),[zoom,setZoom]=useState(1),[network,setNetwork]=useState(!route),[failed,setFailed]=useState(false);const svg=useRef(null);
 useEffect(()=>{setNetwork(!route);setZoom(1)},[route]);
 useEffect(()=>{if(!full)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';const esc=e=>{if(e.key==='Escape')setFull(false)};window.addEventListener('keydown',esc);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',esc)}},[full]);
 const rows=route?.segments.flatMap((seg,i)=>seg.stations.map((name,j)=>({name,color:seg.line.color,line:seg.line.id,first:j===0,last:j===seg.stations.length-1,transfer:i>0&&j===0})))||[];const height=100+rows.length*42;
 function download(){if(!svg.current)return;const xml=new XMLSerializer().serializeToString(svg.current);const url=URL.createObjectURL(new Blob([xml],{type:'image/svg+xml'}));const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=720;c.height=height;c.getContext('2d').drawImage(img,0,0);URL.revokeObjectURL(url);c.toBlob(blob=>{if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mi-ruta-metrobus.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)})};img.src=url}
 return <section className={'mb-map'+(full?' mb-map-full':'')} aria-label="Mapa de Metrobús"><div className="mb-map-tools"><div><button onClick={()=>{setNetwork(true);setZoom(1)}} aria-pressed={network}>Red oficial</button><button disabled={!route} onClick={()=>{setNetwork(false);setZoom(1)}} aria-pressed={!network}>Mi recorrido</button></div><div><button title="Alejar" onClick={()=>setZoom(z=>Math.max(1,z-.5))}><Minus size={17}/></button><button title="Acercar" onClick={()=>setZoom(z=>Math.min(4,z+.5))}><Plus size={17}/></button><button title={full?'Cerrar mapa':'Expandir mapa'} onClick={()=>setFull(!full)}>{full?<X size={17}/>:<Expand size={17}/>}</button>{!network&&route&&<button title="Descargar ruta PNG" onClick={download}><Download size={17}/></button>}</div></div><div className="mb-map-viewport">{network?<>{failed?<p>No se pudo cargar el plano. <a href={official} target="_blank" rel="noreferrer">Abrir mapa oficial</a></p>:<img src={official} alt="Plano oficial de las siete líneas del Metrobús CDMX" style={{width:zoom*100+'%',maxWidth:'none'}} onError={()=>setFailed(true)}/>}</>:<svg ref={svg} xmlns="http://www.w3.org/2000/svg" width="720" height={height} viewBox={`0 0 720 ${height}`} style={{width:zoom*100+'%',height:'auto'}} role="img" aria-label="Diagrama de tu recorrido en Metrobús"><rect width="720" height={height} fill="#fffafa"/><text x="30" y="34" fontFamily="Arial" fontSize="21" fontWeight="bold" fill="#be1830">MI RECORRIDO · METROBÚS CDMX</text>{rows.map((r,i)=><g key={i}><line x1="48" y1={60+i*42} x2="48" y2={102+i*42} stroke={r.color} strokeWidth="7"/><circle cx="48" cy={81+i*42} r={r.first||r.last?9:5} fill="white" stroke={r.color} strokeWidth="3"/><text x="73" y={87+i*42} fontFamily="Arial" fontSize="17" fill="#30252a">{r.name}</text><text x="535" y={87+i*42} fontFamily="Arial" fontSize="13" fill="#6e555d">{r.transfer?'Transbordo · ':''}Línea {r.line}</text></g>)}</svg>}</div><p className="mb-map-note">{network?'Fuente: Metrobús CDMX · Amplía para leer las estaciones.':'Diagrama del recorrido, sin escala geográfica · Cada estación aparece en una fila.'}</p></section>
}
